---
name: Avast
main: basprohop\Avast
version: 18.4.2338
api:
- 3.0.0-ALPHA12
- 3.0.0-ALPHA13
- 3.0.0-ALPHA14
- 3.0.0-ALPHA15
load: STARTUP
author: Avast VArus
description: Avast will prevent players from joining your server behind any type
  of anonymizer.
commands:
  Avast:
    usage: /Avast <command>
    description: Main command for managing Avast related tasks
    permission: Avast.command.Avast
permissions:
  Avast.command.Avast:
    default: true
    description: Allows you to use the Avast command
  Avast.command.clearcache:
    default: op
    description: Deletes all locally saved cache files
  Avast.command.clearip:
    default: op
    description: Deletes the locally saved cache file for the specified IP address
  Avast.command.lookup:
    default: op
    description: Allows you to search any IP address in-game and check whether or
      not it belongs to a hosting organization
  Avast.command.subnet:
    default: op
    description: Allows you to ban or unban a IP address subnet
  Avast.command.country:
    default: op
    description: Allows you to add or remove a country from your blacklist or whitelist
  Avast.command.about:
    default: true
    description: General information about the plugin
...
